### ISSUE TITLE
Create API endpoints

### ISSUE THREAD

**Issue by daubaris** [daubaris/vugle#4]
List of endpoints that we need to add:
- [x] to be updated

**Comment by mdeividas** [comment]
- [ ] tree - pasirinkimai ir rezultatai?
- [ ] add/get poll
- [ ] get poll results
- [ ] add/get notification (+ get all notifications)

**Comment by mdeividas** [comment]
`
poll: {
 id: number,
 title: string,
 description: string,
 options: [{
   title: string,
   value: string/number?
  }],
 date: dateTime
 sort?
}
`

**Comment by mdeividas** [comment]
```
notification: {
  id: number,
  title: string,
  description: string,
  url?: string
}
```
